repos:

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 7d85583be209cb547946c82fbe51f4bc5dd1d017
    hooks:
    - id: clang-format
      args: [--style=Google]
      files: \.(cpp|hpp|c|h))$
      stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
        stages: [commit]
      - id: ruff-format
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
